Repository AxaFrance/react-toolkit, pull requests merged in 2020-10, with the labels that each got.

#694 fix(table-pager): add flexible width when active page number is large
  packages/table/src/Pager/pager.scss
  storybook/storybook/src/packages/table/src/Pager/Pager.stories.js
Labels: hacktoberfest-accepted

#696 fix(new-ds): fix broken link to template pugs
  storybook/design-system/src/components/form/mixins/mixin-form-field-card.pug
  storybook/design-system/src/components/form/mixins/mixin-form-field-checkbox.pug
  storybook/design-system/src/components/form/mixins/mixin-form-field-select.pug
  storybook/design-system/src/components/form/mixins/mixin-form-field-text.pug
  storybook/design-system/src/components/form/mixins/mixin-form-message.pug
  storybook/design-system/src/pages/atoms/badge/templates/infoIcon.pug
  storybook/design-system/src/pages/atoms/button/templates/button-icon.pug
  storybook/design-system/src/pages/atoms/button/templates/button-reverse.pug
  storybook/design-system/src/pages/atoms/button/templates/circle.pug
  storybook/design-system/src/pages/atoms/button/templates/ghost.pug
  storybook/design-system/src/pages/atoms/list/templates/withIcon.pug
  storybook/design-system/src/pages/atoms/popover/templates/classic.pug
  storybook/design-system/src/pages/get-started/how-to-contribute/markdown/content.md
  storybook/design-system/src/pages/molecules/alert/templates/alertComplex.pug
  storybook/design-system/src/pages/molecules/alert/templates/alertComplexDanger.pug
  storybook/design-system/src/pages/molecules/alert/templates/alertSimpleDanger.pug
  storybook/design-system/src/pages/molecules/alert/templates/alertSimpleInfo.pug
  storybook/design-system/src/pages/molecules/alert/templates/alertSimpleSuccess.pug
  storybook/design-system/src/pages/molecules/form-datepicker/templates/form-datepicker.pug
  storybook/design-system/src/pages/molecules/form-file/templates/form-file-list-error.pug
  storybook/design-system/src/pages/molecules/form-file/templates/form-file-list.pug
  storybook/design-system/src/pages/molecules/form-file/templates/form-file.pug
  storybook/design-system/src/pages/molecules/form-pass/templates/form-pass.pug
  storybook/design-system/src/pages/molecules/navigation/templates/classic.pug
  storybook/design-system/src/pages/molecules/steps-new/templates/steps-new-sample2.pug
  storybook/design-system/src/pages/molecules/steps-new/templates/steps-new-sample3.pug
  storybook/design-system/src/pages/molecules/steps-new/templates/steps-new.pug
  storybook/design-system/src/pages/molecules/steps/templates/classic.pug
  storybook/design-system/src/pages/molecules/table/templates/headerCell.pug
  storybook/design-system/src/pages/molecules/table/templates/line.pug
  storybook/design-system/src/pages/molecules/table/templates/status.pug
  storybook/design-system/src/pages/molecules/tabs/templates/tabs-complex.pug
  storybook/design-system/src/pages/molecules/tabs/templates/tabs-long-text.pug
  storybook/design-system/src/pages/molecules/title-bar/templates/title-bar-complex.pug
  storybook/design-system/src/pages/organisms/accordion/templates/accordion-light.pug
  storybook/design-system/src/pages/organisms/accordion/templates/accordion-right-arrow.pug
  storybook/design-system/src/pages/organisms/accordion/templates/accordion.pug
  storybook/design-system/src/pages/organisms/form-filter-inline/templates/form-filter-inline.pug
  storybook/design-system/src/pages/organisms/form-filter/templates/form-filter.pug
  storybook/design-system/src/pages/organisms/header/templates/classic.pug
  storybook/design-system/src/pages/organisms/modal/templates/modal-large.pug
  storybook/design-system/src/pages/organisms/modal/templates/modal-small.pug
  storybook/design-system/src/pages/organisms/modal/templates/modal.pug
  storybook/design-system/src/pages/organisms/paging/templates/classic.pug
  storybook/design-system/src/pages/organisms/panel/templates/panel-selection.pug
  storybook/design-system/src/pages/organisms/panel/templates/panel.pug
  storybook/design-system/src/pages/organisms/restitution/templates/restitution-double.pug
  storybook/design-system/src/pages/organisms/restitution/templates/restitution-more.pug
  storybook/design-system/src/pages/organisms/restitution/templates/restitution.pug
Labels: hacktoberfest-accepted

#701 fix(pug): contributors page production build
  storybook/design-system/gulpfile.babel.js/index.js
Labels: bug

#703 docs: fixed storybook treeview
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#708 build: drop support of old Node.js versions
  CONTRIBUTING.md
  package.json
Labels: hacktoberfest-accepted

#704 Update dependencies
  .babelrc
  .eslintrc
  CONTRIBUTING.md
  azure-pipelines.yml
  babel.config.json
  package-lock.json
  package.json
  packages/Form/Input/card/package.json
  packages/Layout/footer-client/package.json
  packages/Layout/header/src/Name/Name.spec.js
  packages/Layout/header/src/NavBar/NavBar.js
  packages/alert/package.json
  packages/collapse/package.json
  packages/core/package.json
  packages/loader/package.json
  packages/tabs/package.json
  scripts/compile-js.js
  scripts/config.js
  scripts/jest.init.js
  storybook/storybook/.storybook/preview.js
  storybook/storybook/package-lock.json
Labels: hacktoberfest-accepted

#699 fix(Form/Input/Date): Make the glyphicon clickable
  packages/Form/Input/date/src/datepicker.scss
Labels: bug-design, hacktoberfest-accepted

#711 NavBar UX guidelines fixes
  packages/Layout/header/src/NavBar/nav.scss
Labels: hacktoberfest-accepted

#720 Apply fix guidelines
  packages/Layout/footer/src/footer.scss
  packages/Layout/header/src/Infos/infos.scss
  packages/Layout/header/src/Logo/logo.scss
  packages/Layout/header/src/Name/Name.js
  packages/Layout/header/src/Name/__snapshots__/Name.spec.js.snap
  packages/Layout/header/src/Name/name.scss
  packages/Layout/header/src/NavBar/nav.scss
  packages/Layout/header/src/Title/title-bar.scss
  packages/core/src/common/scss/_custom-af-colorsvariables.scss
  packages/core/src/common/scss/colorsList.js
Labels: hacktoberfest-accepted

#722 Update dependencies & moment
  package-lock.json
  package.json
  packages/Form/Input/date-phone/package.json
  packages/Form/Input/date/package.json
Labels: dependencies

#737 build: bump dependencies
  .eslintrc
  package-lock.json
  package.json
  packages/Form/core/src/FieldForm.js
  packages/Form/summary/package.json
  packages/Layout/footer/package.json
  packages/Modal/default/package.json
  packages/Modal/default/src/ModalCore.tsx
  packages/core/package.json
  packages/highlight/package.json
  packages/icon/package.json
  packages/link/package.json
  packages/list/package.json
  packages/loader/package.json
  packages/panel/package.json
  packages/status/package.json
  packages/table/package.json
  packages/title/package.json
  scripts/compile-ts.js
Labels: dependencies

#727 feat(collapse): added onToggleCallback prop on CollapseCardBase
  packages/collapse/src/Accordion.tsx
  packages/collapse/src/Collapse.stories.tsx
Labels: hacktoberfest-accepted

#735 feat(form-input-text): fix design issues
  packages/Form/Input/text/src/inputtext.scss
Labels: bug-design, hacktoberfest-accepted

#770 fix(storybook): change the brandUrl to match the spirit of the project
  .storybook/manager.js
Labels: hacktoberfest-accepted

#772 feat(modal): improve a11y on Modal
  packages/Modal/boolean/package.json
  packages/Modal/boolean/src/ModalBoolean.js
  packages/Modal/boolean/src/ModalBoolean.spec.tsx
  packages/Modal/boolean/src/ModalBoolean.stories.js
  packages/Modal/boolean/src/ModalBoolean.stories.tsx
  packages/Modal/boolean/src/ModalBoolean.tsx
  packages/Modal/boolean/src/__snapshots__/ModalBoolean.spec.tsx.snap
  packages/Modal/boolean/src/index.ts
  packages/Modal/boolean/tsconfig.json
  packages/Modal/default/src/Div.tsx
  packages/Modal/default/src/Footer.ts
  packages/Modal/default/src/Header.ts
  packages/Modal/default/src/HeaderCore.tsx
  packages/Modal/default/src/Modal.tsx
  packages/Modal/default/src/ModalCore.tsx
  packages/Modal/default/src/ModalDefault.stories.tsx
  packages/Modal/default/src/__snapshots__/Modal.spec.tsx.snap
  packages/Modal/default/src/__snapshots__/ModalCore.spec.tsx.snap
Labels: Component: Modal, hacktoberfest-accepted
