Repository AxaFrance/react-toolkit, pull requests merged in 2023-09, with the labels that each got.

#1054 fix(accessibility): use alert and aria-busy for loader
  packages/loader/README.md
  packages/loader/src/Loader.tsx
  packages/loader/src/__tests__/Loader.spec.tsx
Labels: fix, Accessibility

#1049 fix(Infos): missing key in header infos
  packages/Layout/header/src/Infos/Infos.tsx
Labels: good first issue, fix

#1035 test(NumberInput): type a minus sign in a NumberInput
  packages/Form/Input/number/src/NumberInput.stories.tsx
Labels: fix

#1056 ci: fix storybook build for node 18
  package.json
Labels: Storybook, fix

#1061 fix(style): stop regenerating snapshot because of emotion
  jest.config.ts
  package-lock.json
  package.json
  packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelect.spec.tsx.snap
  packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelectInput.spec.tsx.snap
Labels: fix

#1062 build(deps): upgrade postcss package
  package-lock.json
  package.json
Labels: dependencies, Storybook, fix

#1040 fix(accessibility): allow focus on radio inputs
  packages/Form/Input/checkbox/src/checkbox.scss
  packages/Form/Input/choice/src/radio.scss
  packages/Form/Input/radio/src/radio.scss
Labels: fix, Accessibility

#982 feat(Help): add help button content in props
  packages/action/src/button.scss
  packages/button/src/button.scss
  packages/help/src/Help.tsx
  packages/help/src/__tests__/Help.spec.tsx
  packages/help/src/help-custom.scss
Labels: Type: Enhancement

#1038 fix(File): file prototype properties are lost with spread operator
  packages/Form/Input/file/src/File.tsx
  packages/Form/Input/file/src/__tests__/FileLine.spec.tsx
  packages/Form/Input/file/src/__tests__/FileTable.spec.tsx
Labels: fix
