Repository AxaFrance/react-toolkit, pull requests merged in 2024-01, with the labels that each got.

#1104 feat(all form-core): add FieldForm in form-core export file
  packages/all/src/form-core.ts
Labels: Type: Bug

#1102 fix(collapse): stop to regenerate id at each rerender
  packages/collapse/src/CollapseCard.tsx
Labels: Type: Bug

#1103 fix(popover/help/helpinfo): help button contains two button, it desactivate the default onKeyPress
  packages/Form/Input/file/src/__tests__/__snapshots__/FileLine.spec.tsx.snap
  packages/help/src/Help.stories.tsx
  packages/help/src/Help.tsx
  packages/help/src/help-custom.scss
  packages/helpinfo/src/HelpInfo.stories.tsx
  packages/helpinfo/src/help-info.scss
  packages/popover/src/Popover.tsx
  packages/popover/src/__tests__/Popover.spec.tsx
  packages/popover/src/help-custom.scss
  packages/popover/src/popover.scss
Labels: Type: Bug, Accessibility

#1109 feat(title): add property to change heading level and design modifications
  packages/title/README.md
  packages/title/src/Title.stories.tsx
  packages/title/src/Title.tsx
  packages/title/src/__tests__/Title.spec.tsx
  packages/title/src/title.scss
Labels: Type: Enhancement, Type: Bug Design

#1111 fix(design): change title bar subtitle color
  packages/Layout/header/src/Title/title-bar.scss
  packages/core/src/common/scss/_custom-af-colorsvariables.scss
  packages/core/src/common/scss/colorsList.js
Labels: Type: Bug Design

#1113 feat(header): make title-bar sticky by default
  packages/Layout/header/README.md
  packages/Layout/header/src/Title/Title.stories.tsx
  packages/Layout/header/src/Title/Title.tsx
  packages/Layout/header/src/Title/title-bar.scss
  packages/Layout/header/src/__tests__/Title.spec.tsx
  packages/Layout/header/src/__tests__/__snapshots__/Title.spec.tsx.snap
Labels: Type: Bug Design

#1114 fix(title): remove previous title css
  MIGRATION.md
  packages/title/src/title.scss
Labels: Type: Bug Design
