Repository AxaFrance/react-toolkit, pull requests merged in 2024-04, with the labels that each got.

#1136 Init template de vérification d'accessibilité des composants
  .github/CHECK_ACCESSIBILITY_ISSUE.md
Labels: Accessibility

#1173 Bugfix/date null value
  packages/Form/Input/date/src/Date.tsx
  packages/Form/Input/date/src/__tests__/Date.spec.tsx
  packages/Form/Input/date/src/__tests__/DateInput.spec.tsx
  packages/Form/Input/date/src/__tests__/__snapshots__/Date.spec.tsx.snap
  packages/Form/Input/date/src/__tests__/__snapshots__/DateInput.spec.tsx.snap
Labels: fix

#1180 fix(modal): adapt modal z-index to overlap sticky title-bar
  packages/Modal/default/src/modal.scss
Labels: Type: Bug, Type: Bug Design, fix
