Repository AxaFrance/react-toolkit, pull requests merged in 2024-08, with the labels that each got.

#1178 fix(table): use border instead of box-shadow to set th border
  packages/table/src/Table.stories.tsx
  packages/table/src/table.scss
Labels: Type: Bug Design, REPLICATE IN NEW DESIGN SYSTEM

#1176 fix(restitution): change restitution header height
  packages/restitution/src/restitution.scss
Labels: Type: Bug Design, REPLICATE IN NEW DESIGN SYSTEM

#1174 feat(title): augment title bar font-weight (from normal to semibold)
  packages/Layout/header/src/HeaderTitle/title-bar.scss
Labels: Type: Bug Design, fix, REPLICATE IN NEW DESIGN SYSTEM

#1048 Refactor/modal
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  packages/Modal/boolean/README.md
  packages/Modal/boolean/src/ModalBoolean.stories.mdx
  packages/Modal/boolean/src/ModalBoolean.stories.tsx
  packages/Modal/boolean/src/ModalBoolean.tsx
  packages/Modal/boolean/src/__tests__/ModalBoolean.spec.tsx
  packages/Modal/boolean/src/__tests__/__snapshots__/ModalBoolean.spec.tsx.snap
  packages/Modal/boolean/src/index.ts
  packages/Modal/default/README.md
  packages/Modal/default/package.json
  packages/Modal/default/src/Body.tsx
  packages/Modal/default/src/Div.tsx
  packages/Modal/default/src/Footer.tsx
  packages/Modal/default/src/Header.tsx
  packages/Modal/default/src/HeaderBase.tsx
  packages/Modal/default/src/HeaderCore.tsx
  packages/Modal/default/src/Modal.tsx
  packages/Modal/default/src/ModalCore.tsx
  packages/Modal/default/src/ModalDefault.stories.mdx
  packages/Modal/default/src/ModalDefault.stories.tsx
  packages/Modal/default/src/__tests__/Body.spec.tsx
  packages/Modal/default/src/__tests__/Div.spec.tsx
  packages/Modal/default/src/__tests__/Footer.spec.tsx
  packages/Modal/default/src/__tests__/Header.spec.tsx
  packages/Modal/default/src/__tests__/HeaderBase.spec.tsx
  packages/Modal/default/src/__tests__/HeaderCore.spec.tsx
  packages/Modal/default/src/__tests__/Modal.spec.tsx
  packages/Modal/default/src/__tests__/ModalCore.spec.tsx
  packages/Modal/default/src/__tests__/__snapshots__/Body.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/Div.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/Footer.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/Header.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/HeaderBase.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/HeaderCore.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/Modal.spec.tsx.snap
  packages/Modal/default/src/__tests__/__snapshots__/ModalCore.spec.tsx.snap
  packages/Modal/default/src/index.ts
  packages/Modal/default/src/modal.scss
  scripts/jest.init.ts
Labels: Breaking Change, fix, Accessibility

#1016 feat(form)!: use native events for primitive components
  jest.config.ts
  package-lock.json
  package.json
  packages/Form/Input/card/src/CardGroup.tsx
  packages/Form/Input/card/src/CardGroupStateless.tsx
  packages/Form/Input/checkbox/src/Checkbox.tsx
  packages/Form/Input/checkbox/src/CheckboxInput.tsx
  packages/Form/Input/checkbox/src/CheckboxItem.tsx
  packages/Form/Input/checkbox/src/__tests__/CheckboxInput.spec.tsx
  packages/Form/Input/checkbox/src/__tests__/__snapshots__/CheckboxInput.spec.tsx.snap
  packages/Form/Input/choice/src/Choice.tsx
  packages/Form/Input/date/src/Date.tsx
  packages/Form/Input/file/src/File.tsx
  packages/Form/Input/number/src/Number.tsx
  packages/Form/Input/number/src/NumberInput.stories.tsx
  packages/Form/Input/pass/src/Pass.stories.tsx
  packages/Form/Input/pass/src/Pass.tsx
  packages/Form/Input/pass/src/__tests__/Pass.spec.tsx
  packages/Form/Input/radio/src/Radio.tsx
  packages/Form/Input/radio/src/RadioItem.tsx
  packages/Form/Input/radio/src/__tests__/__snapshots__/Radio.spec.tsx.snap
  packages/Form/Input/select-multi/src/MultiSelect.stories.tsx
  packages/Form/Input/select-multi/src/MultiSelect.tsx
  packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelect.spec.tsx.snap
  packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelectInput.spec.tsx.snap
  packages/Form/Input/select/src/Select.tsx
  packages/Form/Input/select/src/SelectBase.tsx
  packages/Form/Input/slider/src/Slider.tsx
  packages/Form/Input/switch/src/Switch.tsx
  packages/Form/Input/text/src/Text.tsx
  packages/Form/Input/textarea/src/Textarea.tsx
  packages/Form/core/src/__tests__/__snapshots__/withInput.spec.tsx.snap
  packages/Form/core/src/__tests__/withInput.spec.tsx
  packages/Form/core/src/index.ts
  packages/Form/core/src/withInput.tsx
  packages/Form/core/src/withIsVisible.tsx
  packages/all/src/form-core.ts
Labels: Breaking Change
