Repository AxaFrance/react-toolkit, pull requests merged in 2024-07, with the labels that each got.

#1189 fix(Select): remove select option when defaultValue is defined
  packages/Form/Input/select/src/Select.tsx
Labels: good first issue, Type: Bug Design

#1195 feat: mark old step form design as deprecated
  packages/Form/steps/src/Steps.stories.tsx
  packages/Form/steps/src/step-form.scss
Labels: Type: Bug Design

#1182 ci: fix sonar action version
  .github/workflows/toolkit-sonar.yml
Labels: fix
